GODLIST = [
    'Achilles', 'Agni', 'Ah_Muzen_Cab', 'Ah_Puch', 'Amaterasu', 'Anhur', 'Anubis', 'Ao_Kuang', 'Aphrodite', 
    'Apollo', 'Arachne', 'Ares', 'Artemis', 'Artio', 'Athena', 'Atlas', 'Awilix', 'Baba_Yaga', 
    'Bacchus', 'Bakasura', 'Bake_Kujira', 'Baron_Samedi', 'Bastet', 'Bellona', 'Cabrakan', 'Camazotz', 'Cerberus', 
    'Chaac', 'Chang%27e', 'Charon', 'Charybdis', 'Chernobog', 'Chiron', 'Chronos', 'Cliodhna', 'Cthulhu', 
    'Cu_Chulainn', 'Cupid', 'Da_Ji', 'Danzaburou', 'Discordia', 'Erlang_Shen', 'Eset', 'Fafnir', 'Fenrir', 
    'Freya', 'Ganesha', 'Geb', 'Gilgamesh', 'Guan_Yu', 'Hachiman', 'Hades', 'He_Bo', 'Heimdallr', 'Hel', 
    'Hera', 'Hercules', 'Horus', 'Hou_Yi', 'Hun_Batz', 'Ishtar', 'Ix_Chel', 'Izanami', 'Janus', 'Jing_Wei', 
    'Jormungandr', 'Kali', 'Khepri', 'King_Arthur', 'Kukulkan', 'Kumbhakarna', 'Kuzenbo', 'Lancelot', 'Loki', 
    'Maman_Brigitte', 'Martichoras', 'Maui', 'Medusa', 'Mercury', 'Merlin', 'Morgan_Le_Fay', 'Mulan', 'Ne_Zha', 
    'Neith', 'Nemesis', 'Nike', 'Nox', 'Nu_Wa', 'Nut', 'Odin', 'Olorun', 'Osiris', 'Pele', 'Persephone', 
    'Poseidon', 'Ra', 'Raijin', 'Rama', 'Ratatoskr', 'Ravana', 'Scylla', 'Serqet', 'Set', 'Shiva', 'Skadi', 
    'Sobek', 'Sol', 'Sun_Wukong', 'Surtr', 'Susano', 'Sylvanus', 'Terra', 'Thanatos', 'The_Morrigan', 'Thor', 
    'Thoth', 'Tiamat', 'Tsukuyomi', 'Tyr', 'Ullr', 'Vamana', 'Vulcan', 'Xbalanque', 'Xing_Tian', 
    'Yemoja', 'Ymir', 'Yu_Huang', 'Zeus', 'Zhong_Kui'
 ]

BASE_URL = 'https://smite.fandom.com/wiki/'

CONSUMABLE_ITEMS = [
    "Baba's Brew", 'Runic Bomb', 'Healing Potion', 'Mana Potion', 'Multi Potion', 'Ward', 
    'Proximity Ward', 'Raven Ward', 'Sentry Ward', "Baron's Brew", 'Chalice of Healing', 
    'Chalice of the Oracle', 'Potion of Power', 'Elixir of Defense', 'Elixir of Power'
    ]

ITEMS = [
    'Relic', 'Shard Relic', 'Golden Shard', 'Horn Shard', 'Sturdy Shard', 'Vibrant Shard', 
    'Vision Shard', 'Wing Shard', 'Aegis Amulet', 'Blink Rune', 'Bracer of Radiance', 
    'Bracer of Radiance', 'Cloak of Meditation', 'Divine Barrier', 'Heavenly Wings', 'Heavenly Wings', 
    'Horrific Emblem', 'Magic Shell', 'Purification Beads', 'Shield of Thorns', 'Shield of Thorns', 
    'Sundering Spear', 'Sundering Spear', 'Teleport Fragment', 'Greater Aegis Amulet', 'Greater Blink Rune', 
    'Greater Bracer of Radiance', 'Greater Bracer of Radiance', 'Greater Cloak of Meditation', 
    'Greater Divine Barrier', 'Greater Heavenly Wings', 'Greater Heavenly Wings', 'Greater Horrific Emblem', 
    'Greater Horrific Emblem', 'Greater Magic Shell', 'Greater Purification Beads', 'Greater Shield of Thorns', 
    'Greater Shield of Thorns', 'Greater Sundering Spear', 'Greater Sundering Spear', 'Greater Teleport Fragment', 
    'Aegis of Acceleration', 'Blessed Barrier', 'Bracer of Brilliance', 'Bracer of Brilliance', 
    'Cloak of the Ascetic', 'Cloak of the Ascetic', 'Emblem of Increasing Peril', 'Emblem of Increasing Peril', 
    'Entangling Wings', 'Entangling Wings', 'Persistent Teleport', 'Phantom Shell', 'Scorching Blink Rune', 
    'Sundering Blast', 'Sundering Blast', 'Temporal Beads', 'Thorns of Judgement', 'Thorns of Judgement', 
    "Protector's Mask", "Sentinel's Gift", "Sentinel's Gift", 'Benevolence', 'Benevolence', "Bumba's Dagger", 
    'Tainted Steel', 'War Flag', 'Bluestone Pendant', "Death's Toll", 'Eye of the Jungle', 'Eye of the Jungle', 
    "Fighter's Mask", 'Gilded Arrow', 'Gilded Arrow', 'Leather Cowl', 'Manikin Scepter', 'Manikin Scepter', 
    "Protector's Mask", 'Vampiric Shroud', 'Vampiric Shroud', 'Warding Sigil', "Warrior's Axe", "Warrior's Axe", 
    'Conduit Gem', 'Conduit Gem', 'Sands of Time', "Sentinel's Boon", "Sentinel's Embrace", "Sentinel's Embrace", 
    'Compassion', 'Heroism', 'Spartan Flag', 'War Banner', "Lono's Mask", "Lono's Mask", "Bumba's Hammer", "Bumba's Spear", 
    "Bumba's Spear", 'Axe of Animosity', 'Blood-soaked Shroud', 'Blood-soaked Shroud', 'Bluestone Brooch', 
    'Bluestone Brooch', 'Corrupted Bluestone', "Death's Embrace", "Death's Temper", 'Diamond Arrow', "Hunter's Cowl", 
    'Infused Sigil', 'Infused Sigil', "Leader's Cowl", 'Manikin Hidden Blade', 'Manikin Hidden Blade', 'Manikin Mace', 
    'Manikin Mace', 'Ornate Arrow', 'Protector of the Jungle', "Rangda's Mask", 'Sacrificial Shroud', 'Seer of the Jungle', 
    'Sigil of the Old Guard', 'Sigil of the Old Guard', 'Sundering Axe', "Archmage's Gem", "Archmage's Gem", 'Gem of Focus', 
    'Pendulum of Ages', 'Tainted Amulet', 'Tainted Breastplate', 'The Alternate Timeline', 'Magic Acorn', 'Mystical Earrings', 
    'Ancient Blade', 'Lost Artifact', 'Short Bow', 'Breastplate', 'Cloak', 'Emerald Ring', 'Glowing Emerald', 'Katana', 
    'Light Blade', 'Morningstar', 'Rebound Buckler', 'Spiked Gauntlet', 'Tiny Trinket', 'Blessed Scepter', 'Cudgel', 'Druid Stone', 
    'Enchanted Kusari', 'Iron Mail', 'Mace', 'Magic Focus', 'Restoring Wand', 'Round Shield', 'Spellbook', 'Talisman', 
    'Uncommon Staff', 'Hidden Dagger', 'Gem of Fate', 'Gem of Fate', 'Lively Acorn', 'Lively Acorn', 'Nettle Acorn', 
    'Nettle Acorn', 'Charged Bow', 'Bound Gauntlet', 'Silver Breastplate', "Adventurer's Blade", "Cleric's Cloak", 
    'Enchanted Trinket', 'Fatalis', 'Tower Shield', 'Warded Shield', 'Charged Morningstar', "Hydra's Star", 'Rose Spike Earrings', 
    'Silver Breastplate', 'Tower Shield', 'Warded Shield', 'Bound Gauntlet', 'Bronze Mail', 'Emerald Mail', 'Emerald Talisman', 
    'Fortress Shield', "Hunter's Bow", 'Silver Talisman', 'Silver Talisman', 'Spellbound Kusari', 'Spellbound Kusari', 
    'Steel Crest', 'Thousand Fold Blade', "Daimyo's Kusari", 'Enchanted Ring', 'Gleaming Ear Cuffs', "Sorcerer's Staff", 
    'Splendid Scepter', 'Book of Souls', 'Emerald Mail', 'Enchanted Spear', 'Fortified Scepter', 'Heavy Hammer', 'Ritual Blade', 
    'Rod of Healing', 'Short Sword', 'Short Sword', 'Balanced Blade', 'Cursed Gauntlet', 'Emerald Talisman', 'Enchanted Ring', 
    'Enchanted Stone', 'Fatalis', 'Heavy Hammer', 'Jeweled Studs', 'Restored Artifact', 'Restored Artifact', "Sage's Stone", 
    'Steel Mail', 'Steel Mail', 'Talon Trinket', 'Talon Trinket', 'Heavy Mace', 'Apprentice Staff', 'Cloak of Concentration', 
    'Cursed Orb', 'Honed Edge', "Knight's Shield", 'Spell Focus', "Warrior's Bane", 'Apprentice Staff', 'Honed Edge', 
    "Knight's Shield", "Cannoneer's Cuirass", 'Relic Dagger', 'Winged Blade', 'Winged Blade', 'Lotus Sickle', 'Lotus Sickle', 
    'Sovereignty', 'Bristlebush Acorn', 'Bristlebush Acorn', 'Evergreen Acorn', 'Evergreen Acorn', 'Heartward Amulet', 
    'Thickbark Acorn', 'Thickbark Acorn', 'Thistlethorn Acorn', 'Thistlethorn Acorn', 'Heartward Amulet', "Odysseus' Bow", 
    "Oni Hunter's Garb", 'Sovereignty', 'Stone of Gaia', 'Stone of Gaia', 'Stormseeker', 'Ancile', 'Ichaival', "Magi's Cloak", 
    'Phalanx', 'Phalanx', 'Talisman of Energy', 'Blackthorn Hammer', 'Equinox', 'Erosion', "Genji's Guard", 'Griffonwing Earrings', 
    'Mail of Renewal', 'Mail of Renewal', 'Shadowdrinker', 'Shadowdrinker', "Shogun's Kusari", 'Stone Cutting Sword', 
    'The Executioner', 'Void Doumaru', 'Absolution', "Berserker's Shield", 'Breastplate of Regrowth', 'Breastplate of Regrowth', 
    'Breastplate of Valor', 'Contagion', 'Contagion', "Emperor's Armor", 'Frostbound Hammer', 'Frostbound Hammer', 
    "Pythagorem's Piece", 'Soul Eater', 'Telkhines Ring', "Archdruid's Fury", 'Demonic Grip', 'Demonic Grip', 
    "Devourer's Gauntlet", 'Fae-Blessed Hoops', "Gladiator's Shield", "Hydra's Lament", "Hydra's Lament", "Jotunn's Wrath", 
    'Last Gasp', "Manticore's Spikes", 'Midgardian Mail', 'Pestilence', 'Polynomicon', 'Spectral Armor', 'Spectral Armor', 
    'Stone Cutting Sword', 'Stone of Binding', 'Abyssal Stone', 'Abyssal Stone', 'Bladed Boomerang', 'Bladed Boomerang', 
    'Dawnbringer', 'Gauntlet of Thebes', 'Prophetic Cloak', "Pythagorem's Piece", 'Runeforged Hammer', 'Shield of the Phoenix', 
    'Soul Gem', 'Spear of Desolation', 'Spear of Desolation', 'Asi', "Bancroft's Talon", "Brawler's Beat Stick", 'Caduceus Club', 
    "Charon's Coin", 'Crimson Claws', 'Dawnbringer', 'Demon Blade', 'Last Gasp', 'Mystical Mail', 'Pridwen', 'Ring of Hecate', 
    "Sekhmet's Scepter", "Sekhmet's Scepter", 'Spear of the Magus', 'Spirit Robe', 'Void Shield', 'Divine Ruin', 'Divine Ruin', 
    'Gem of Isolation', 'Rejuvenating Heart', 'Rejuvenating Heart', 'Vital Amplifier', 'Arondight', "Bancroft's Talon", 
    'Bloodforge', 'Book of Thoth', 'Curseweaver', 'Dominance', 'Obsidian Shard', 'Obsidian Shard', 'Rage', 'Serrated Edge', 
    "Shifter's Shield", 'The Crusher', 'The Crusher', "Titan's Bane", 'Transcendence', "Warlock's Staff", 'Duality', 
    'Silverbranch Bow', 'Staff of Myrddin', 'Staff of Myrddin', 'Tablet of Destinies', 'Tablet of Destinies', 'Bloodforge', 
    "Chronos' Pendant", 'Cyclopean Ring', 'Cyclopean Ring', 'Ethereal Staff', 'Ethereal Staff', 'Hastened Fatalis', 
    'Mantle of Discord', "Qin's Sais", "Qin's Sais", 'Rod of Asclepius', "Sphinx's Baubles", 'Fail-not', 'Soul Reaver', 
    'Soul Reaver', "Typhon's Fang", 'Doom Orb', 'Heartseeker', 'Rod of Tahuti', 'Deathbringer', 'Bewitched Dagger', 
    'Eldritch Dagger', 'Amulet of Silence', 'Amulet of the Stronghold', 'Amulet of the Stronghold', "Magi's Revenge", 
    "Magi's Shelter", 'Envenomed Executioner', 'Envenomed Executioner', 'The Ferocious Executioner', 'Breastplate of Determination', 
    'Breastplate of Vigilance', 'Breastplate of Vigilance', "Jotunn's Cunning", "Jotunn's Vigor", 'Flameforged Hammer', 
    'Runebreaking Hammer', "Bancroft's Claw", 'Glorious Pridwen', "Nimble Bancroft's Talon", 'Reverent Pridwen', 'Reverent Pridwen', 
    'Calamitous Rod of Tahuti', 'Perfected Rod of Tahuti', 'Devoted Deathbringer', 'Malicious Deathbringer', 'Evolved Book of Thoth', 
    "Evolved Charon's Coin", "Evolved Devourer's Gauntlet", 'Evolved Gauntlet of Thebes', 'Evolved Prophetic Cloak', 
    'Evolved Prophetic Cloak', 'Evolved Rage', 'Evolved Soul Eater', 'Evolved Transcendence', "Evolved Warlock's Staff"
    ]